/**
 * /calibration/[week] — single weekly calibration log entry.
 *
 * Phase C6 of the post-pivot rolling plan. Renders the raw markdown
 * from `reports/calibration/YYYY-WW.md` as a `<pre>` block (no rich
 * markdown rendering yet — the calibration log is intentionally
 * minimal; the founder-written essays at /essays carry the voice).
 */

import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getCalibrationLog } from "@/lib/calibration-loader.server";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ week: string }>;
}): Promise<Metadata> {
  const { week } = await params;
  return {
    title: `Calibration log. Week ${week}. ContentRX`,
    description: `Weekly calibration log entry for ISO week ${week}.`,
  };
}

export default async function CalibrationWeekPage({
  params,
}: {
  params: Promise<{ week: string }>;
}) {
  const { week } = await params;
  const entry = getCalibrationLog(week);
  if (!entry) notFound();

  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <p className="text-xs">
        <Link
          href="/calibration"
          className="text-quiet hover:underline"
        >
          ← Back to calibration log
        </Link>
      </p>
      <header className="mt-4 mb-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-quiet">
          Calibration log
        </p>
        <h1 className="mt-2 text-2xl font-semibold">
          Week {entry.week}
        </h1>
        <p className="mt-2 text-xs text-quiet">
          Generated {formatIso(entry.modified_at)} ·{" "}
          {entry.size_bytes.toLocaleString()} bytes
        </p>
      </header>

      <article className="rounded-lg border border-line bg-raised p-6">
        <pre className="whitespace-pre-wrap break-words font-sans text-sm leading-relaxed text-default">
{entry.contents}
        </pre>
      </article>

      <p className="mt-6 text-xs text-quiet">
        Source:{" "}
        <a
          href={`https://github.com/thenewforktimes/contentRX/blob/main/reports/calibration/${entry.filename}`}
          className="underline underline-offset-2"
        >
          reports/calibration/{entry.filename}
        </a>
        . Generated by the Monday cron at{" "}
        <code className="font-mono">.github/workflows/calibration_log.yml</code>.
      </p>
    </main>
  );
}

function formatIso(iso: string): string {
  if (!iso) return "";
  try {
    return new Date(iso).toISOString().slice(0, 16).replace("T", " ");
  } catch {
    return iso;
  }
}
