/**
 * /calibration/[week] — single weekly calibration log entry.
 *
 * Phase C6 of the post-pivot rolling plan. Renders the templated
 * markdown emitted by `reports/calibration/generate.py` into proper
 * JSX via `<CalibrationMarkdown>`. The page used to dump the file
 * as a `<pre>` block, which produced an illegible wall of literal
 * `#`, `**`, `_`, and backtick characters — that's fixed.
 *
 * Timestamp source: the markdown body's `_Generated TIMESTAMP._`
 * line, extracted by the parser. Vercel's build environment doesn't
 * preserve `fs.statSync().mtime`, which produced a "Generated
 * 2018-10-20" header before this fix. The body-embedded timestamp
 * is the source of truth — it's what the generator stamped at
 * write time.
 */

import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  CalibrationMarkdown,
  parseCalibrationMarkdown,
} from "@/lib/calibration-markdown";
import { getCalibrationLog } from "@/lib/calibration-loader.server";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ week: string }>;
}): Promise<Metadata> {
  const { week } = await params;
  return {
    title: `Calibration log. Week ${week}. ContentRX`,
    description: `Weekly calibration log entry for ISO week ${week}.`,
  };
}

export default async function CalibrationWeekPage({
  params,
}: {
  params: Promise<{ week: string }>;
}) {
  const { week } = await params;
  const entry = getCalibrationLog(week);
  if (!entry) notFound();

  // Prefer the body-embedded timestamp; fall back to fs mtime only
  // if the body somehow lacks one (older logs that predate the
  // generator's stamp line).
  const { generated_at } = parseCalibrationMarkdown(entry.contents);
  const displayTimestamp = generated_at ?? entry.modified_at;

  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <p className="text-xs">
        <Link
          href="/calibration"
          className="text-quiet hover:underline"
        >
          ← Back to calibration log
        </Link>
      </p>
      <header className="mt-4 mb-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-quiet">
          Calibration log
        </p>
        <h1 className="mt-2 text-2xl font-semibold">
          Week {entry.week}
        </h1>
        <p className="mt-2 text-xs text-quiet">
          Generated {formatIso(displayTimestamp)}
        </p>
      </header>

      <article className="rounded-lg border border-line bg-raised p-6">
        <CalibrationMarkdown md={entry.contents} />
      </article>

      <p className="mt-6 text-xs text-quiet">
        Source:{" "}
        <a
          href={`https://github.com/thenewforktimes/contentRX/blob/main/reports/calibration/${entry.filename}`}
          className="underline underline-offset-2"
        >
          reports/calibration/{entry.filename}
        </a>
        . Generated by the Monday cron at{" "}
        <code className="font-mono">.github/workflows/calibration_log.yml</code>.
      </p>
    </main>
  );
}

function formatIso(iso: string): string {
  if (!iso) return "";
  try {
    return new Date(iso).toISOString().slice(0, 16).replace("T", " ") + " UTC";
  } catch {
    return iso;
  }
}
