/**
 * /dashboard/graduation — Graduation approval surface.
 *
 * Human-eval build plan Session 11. Reads the committed readiness
 * report (`evals/graduation/readiness.json`, generated by
 * `tools/graduation_metrics.py`) plus the current `graduation_status`
 * rows from the DB. Shows eligible standards with a one-click
 * approve button (admin-gated), plus a read-only list of every
 * standard grouped by current level.
 *
 * The UI is a reviewer surface — the data-driven decision is already
 * made by the metrics tool. Approval here is oversight, not
 * re-derivation.
 */

import { auth } from "@clerk/nextjs/server";
import { unstable_cache } from "next/cache";
import Link from "next/link";
import { redirect } from "next/navigation";
import fs from "node:fs";
import path from "node:path";
import {
  LEVEL_CONSEQUENCES,
  canApproveGraduation,
  demoteOneStep,
  listGraduationStatuses,
  type GraduationLevel,
} from "@/lib/graduation";
import { ApproveButton } from "./approve-button";
import { DemoteButton } from "./demote-button";

interface CriteriaBlock {
  eligible?: boolean;
  criteria?: {
    sample_size?: { value?: number | null; threshold?: number };
    kappa?: { value?: number | null; threshold?: number };
    raw_agreement?: { value?: number | null; threshold?: number };
    override_rate?: { value?: number | null; threshold?: number };
    counterparts?: {
      count_effective?: number;
      tier_minimum?: number;
      pass_rate?: number | null;
    };
  };
}

interface StandardReadiness {
  standard_id: string;
  recommended_level?: GraduationLevel;
  prevalence?: number | null;
  autonomous?: CriteriaBlock;
  batch_approval?: CriteriaBlock;
}

interface Readiness {
  generated_at?: string;
  measured_ceiling?: number;
  standards?: StandardReadiness[];
  by_level?: Record<string, number>;
}

// Wrapped in unstable_cache so concurrent requests (and successive
// renders) reuse the parsed JSON instead of re-reading + re-parsing
// readiness.json on every navigation. The file is rewritten by a
// nightly cron (tools/graduation_metrics.py); 1h revalidate is
// well within freshness budget while collapsing typical traffic.
const readReadiness = unstable_cache(
  async (): Promise<Readiness | null> => {
    const p = path.join(process.cwd(), "evals", "graduation", "readiness.json");
    try {
      if (!fs.existsSync(p)) return null;
      return JSON.parse(fs.readFileSync(p, "utf-8")) as Readiness;
    } catch {
      return null;
    }
  },
  ["dashboard-graduation-readiness"],
  { revalidate: 3600 },
);

export default async function GraduationPage() {
  const { userId: clerkId } = await auth();
  if (!clerkId) {
    redirect("/sign-in?redirect_url=/dashboard/graduation");
  }

  const canApprove = canApproveGraduation(clerkId);
  const readiness = await readReadiness();
  const dbRows = await listGraduationStatuses();
  const dbByStandard = new Map(dbRows.map((r) => [r.standardId, r]));

  const standards = readiness?.standards ?? [];
  const eligible = standards.filter(
    (s) => (s.recommended_level ?? "robo_labels") !== "robo_labels",
  );

  return (
    <div className="flex flex-col gap-6">
      <header>
        <p className="text-xs font-mono uppercase tracking-widest text-neutral-500">
          Graduation ladder
        </p>
        <h1 className="mt-2 text-2xl font-semibold">Eligible promotions</h1>
        <p className="mt-1 text-sm text-neutral-600 dark:text-neutral-400">
          The ladder&apos;s six hard-gate criteria live in{" "}
          <code className="font-mono text-xs">tools/graduation_metrics.py</code>.
          Approval here is oversight — the data-driven decision is already
          made. See{" "}
          <code className="font-mono text-xs">evals/graduation/README.md</code>
          .
        </p>
        {readiness?.generated_at && (
          <p className="mt-1 text-xs text-neutral-500">
            Readiness computed {new Date(readiness.generated_at).toLocaleString()}
            {typeof readiness.measured_ceiling === "number" && (
              <> · measured ceiling {readiness.measured_ceiling.toFixed(2)}</>
            )}
          </p>
        )}
      </header>

      {!readiness && (
        <section className="rounded-md border border-dashed border-neutral-300 p-6 text-sm text-neutral-500 dark:border-neutral-700">
          No readiness report found. Run{" "}
          <code className="rounded bg-neutral-100 px-1 py-0.5 font-mono text-xs dark:bg-neutral-900">
            python3 tools/graduation_metrics.py compute
          </code>{" "}
          locally and commit the output at{" "}
          <code className="font-mono text-xs">evals/graduation/readiness.json</code>
          .
        </section>
      )}

      {readiness && eligible.length === 0 && (
        <section className="rounded-md border border-dashed border-neutral-300 p-6 text-sm text-neutral-500 dark:border-neutral-700">
          No standards are eligible for promotion right now. The ladder waits
          for each of the six hard-gate criteria — sample size, κ vs Robo,
          raw-agreement floor, MCC (when prevalence is low), override rate,
          and counterpart tier — before recommending a promotion.
        </section>
      )}

      {eligible.length > 0 && (
        <section className="flex flex-col gap-3">
          {eligible.map((s) => {
            const currentLevel: GraduationLevel =
              (dbByStandard.get(s.standard_id)?.level as GraduationLevel) ??
              "robo_labels";
            const targetLevel = (s.recommended_level ??
              "robo_labels") as GraduationLevel;
            const block =
              targetLevel === "autonomous" ? s.autonomous : s.batch_approval;
            return (
              <article
                key={s.standard_id}
                className="flex flex-col gap-3 rounded-lg border border-emerald-300 bg-emerald-50/50 p-5 text-sm dark:border-emerald-900 dark:bg-emerald-950/30"
              >
                <header className="flex items-start justify-between gap-4">
                  <div>
                    <p className="font-mono text-sm font-semibold">
                      {s.standard_id}
                    </p>
                    <p className="text-xs text-neutral-700 dark:text-neutral-300">
                      {currentLevel} → <strong>{targetLevel}</strong>
                    </p>
                  </div>
                  {canApprove ? (
                    <ApproveButton
                      standardId={s.standard_id}
                      targetLevel={targetLevel}
                      criteriaSnapshot={block ?? {}}
                    />
                  ) : (
                    <span className="rounded-full bg-neutral-200 px-2 py-0.5 text-xs font-medium text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300">
                      admin only
                    </span>
                  )}
                </header>
                <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
                  {block?.criteria?.sample_size && (
                    <CriterionPill
                      label="Sample"
                      value={`${block.criteria.sample_size.value ?? "—"}`}
                      threshold={`≥ ${block.criteria.sample_size.threshold}`}
                    />
                  )}
                  {block?.criteria?.kappa && (
                    <CriterionPill
                      label="κ"
                      value={
                        typeof block.criteria.kappa.value === "number"
                          ? block.criteria.kappa.value.toFixed(3)
                          : "—"
                      }
                      threshold={`≥ ${(block.criteria.kappa.threshold ?? 0).toFixed(3)}`}
                    />
                  )}
                  {block?.criteria?.raw_agreement && (
                    <CriterionPill
                      label="Raw"
                      value={
                        typeof block.criteria.raw_agreement.value === "number"
                          ? `${(block.criteria.raw_agreement.value * 100).toFixed(1)}%`
                          : "—"
                      }
                      threshold={`≥ ${((block.criteria.raw_agreement.threshold ?? 0) * 100).toFixed(0)}%`}
                    />
                  )}
                  {block?.criteria?.override_rate && (
                    <CriterionPill
                      label="Override"
                      value={
                        typeof block.criteria.override_rate.value === "number"
                          ? `${(block.criteria.override_rate.value * 100).toFixed(1)}%`
                          : "—"
                      }
                      threshold={`< ${((block.criteria.override_rate.threshold ?? 0) * 100).toFixed(0)}%`}
                    />
                  )}
                </div>
                <p className="text-xs text-neutral-700 dark:text-neutral-300">
                  <strong>What changes:</strong> {LEVEL_CONSEQUENCES[targetLevel]}
                </p>
              </article>
            );
          })}
        </section>
      )}

      <section>
        <h2 className="mb-3 text-sm font-semibold">All standards by level</h2>
        {readiness ? (
          <LevelBreakdown
            readiness={readiness}
            dbByStandard={dbByStandard}
            canApprove={canApprove}
          />
        ) : (
          <p className="text-xs text-neutral-500">(no readiness loaded)</p>
        )}
      </section>

      <Link
        href="/dashboard/cadence"
        className="text-xs text-neutral-600 underline underline-offset-2 dark:text-neutral-400"
      >
        ← Back to daily queue
      </Link>
    </div>
  );
}

function CriterionPill({
  label,
  value,
  threshold,
}: {
  label: string;
  value: string;
  threshold: string;
}) {
  return (
    <div className="rounded-md border border-neutral-200 bg-white p-2 dark:border-neutral-800 dark:bg-neutral-950">
      <p className="text-[10px] uppercase tracking-wider text-neutral-500">
        {label}
      </p>
      <p className="mt-1 font-mono text-sm font-semibold">{value}</p>
      <p className="text-[10px] text-neutral-500">{threshold}</p>
    </div>
  );
}

function LevelBreakdown({
  readiness,
  dbByStandard,
  canApprove,
}: {
  readiness: Readiness;
  dbByStandard: Map<string, { level: GraduationLevel | string }>;
  canApprove: boolean;
}) {
  const byLevel: Record<GraduationLevel, string[]> = {
    robo_labels: [],
    batch_approval: [],
    autonomous: [],
  };
  for (const s of readiness.standards ?? []) {
    const lvl =
      (dbByStandard.get(s.standard_id)?.level as GraduationLevel) ??
      (s.recommended_level ?? "robo_labels");
    if (lvl in byLevel) {
      byLevel[lvl as GraduationLevel].push(s.standard_id);
    }
  }

  const order: GraduationLevel[] = ["autonomous", "batch_approval", "robo_labels"];
  return (
    <div className="flex flex-col gap-4">
      {order.map((lvl) => (
        <div
          key={lvl}
          className="rounded-md border border-neutral-200 p-4 dark:border-neutral-800"
        >
          <p className="font-mono text-xs font-semibold">{lvl}</p>
          <p className="text-xs text-neutral-500">{LEVEL_CONSEQUENCES[lvl]}</p>
          <p className="mt-2 text-xs">
            <strong>{byLevel[lvl].length}</strong> standards
          </p>
          {byLevel[lvl].length === 0 ? (
            <p className="mt-1 font-mono text-[10px] text-neutral-500">(none)</p>
          ) : (
            <ul className="mt-2 flex flex-col gap-1">
              {byLevel[lvl].map((standardId) => (
                <li
                  key={standardId}
                  className="flex items-center justify-between gap-2 rounded-md border border-neutral-100 bg-white px-2 py-1 font-mono text-[11px] dark:border-neutral-900 dark:bg-neutral-950"
                >
                  <span>{standardId}</span>
                  {canApprove && lvl !== "robo_labels" && (
                    <DemoteButton
                      standardId={standardId}
                      currentLevel={lvl}
                      targetLevel={demoteOneStep(lvl)}
                    />
                  )}
                </li>
              ))}
            </ul>
          )}
        </div>
      ))}
    </div>
  );
}
