/**
 * Case-study registry — human-eval build plan Sessions 26–28.
 *
 * The three case studies in the plan (OSS project runs) require
 * maintainer contact + live API runs + maintainer approval before
 * publishing. This file is the load-bearing piece on the docs-site
 * side: the registry lists every published case study, and the CI
 * guard in `scripts/check_case_study_approval.py` blocks merges on
 * any registry entry that doesn't carry `maintainer_approval: true`.
 *
 * Publishing workflow (for Robo, not for automation):
 *
 *   1. Pick a candidate from `evals/case_study_candidates.json`
 *      (generated by `tools/case_study_candidates.py`).
 *   2. Contact the maintainers via the repo's issue tracker or a
 *      public channel. Get explicit written approval.
 *   3. Run ContentRX against the project (CLI --batch against a
 *      string corpus you extracted; attribute the source files).
 *   4. Draft the MDX at
 *      `docs-site/app/case-studies/<slug>/page.mdx`. Copy the shape
 *      of `docs-site/content/case-studies/_template.mdx`.
 *   5. Add an entry to `CASE_STUDIES` below. The meta object must
 *      set `maintainer_approval: true` with `approved_by` + `approved_at`.
 *      Without it the CI guard blocks the merge.
 *   6. Open the PR. The guard enforces the invariant; a human reviews
 *      the prose.
 */

export type JudgmentCall = {
  /** Short (<= 80 char) summary of the judgment call. */
  summary: string;
  /** The standard ContentRX flagged. */
  standard_id: string;
  /** The moment context. */
  moment: string;
  /** 1-3 sentences on why this is a judgment call, not a rule-based catch. */
  critique: string;
  /** Optional — link to the offending line in the project's source. */
  source_url?: string;
};

export type CaseStudyMeta = {
  /** URL slug — must match the folder name at app/case-studies/<slug>. */
  slug: string;
  project_name: string;
  project_url: string;
  project_repo_url?: string;
  /** License the project ships under. Nullable for projects with no clear license. */
  project_license: string | null;
  /** ISO 8601 date. */
  published_at: string;
  /**
   * Hard gate — the CI guard rejects any registry entry that doesn't
   * set this to `true`. Rejects a missing value too; we require an
   * explicit affirmative.
   */
  maintainer_approval: true;
  /** Who on the maintainer side approved (handle, email, or "issue #NNN"). */
  approved_by: string;
  /** ISO 8601 date of the maintainer's approval. */
  approved_at: string;
  /** One-line teaser for the index page. */
  teaser: string;
  /**
   * At least three judgment calls — the plan's success criterion.
   * The CI guard enforces the three-minimum so half-finished drafts
   * can't sneak past.
   */
  judgment_calls: JudgmentCall[];
  /** Optional — linked PRs on the project's repo that came out of the review. */
  linked_prs?: Array<{ url: string; title: string }>;
};

/**
 * Published case studies. Empty at scaffolding time; each of the
 * three sessions (26, 27, 28) adds one entry once the maintainer
 * approval + live run are complete.
 */
export const CASE_STUDIES: CaseStudyMeta[] = [];

export function getCaseStudy(slug: string): CaseStudyMeta | null {
  return CASE_STUDIES.find((s) => s.slug === slug) ?? null;
}

export function allCaseStudySlugs(): string[] {
  return CASE_STUDIES.map((s) => s.slug);
}
