/**
 * Standards loader for the docs site.
 *
 * Imports `standards_library.json` so webpack bundles it into the build
 * output. The file is generated by the `prebuild` / `predev` npm
 * scripts, which cp the canonical engine copy from
 * `../src/content_checker/standards/standards_library.json`.
 *
 * Why not readFileSync(__dirname + ...)? Next.js bundles the compiled
 * page code into `.next/server/app/.../page.js`, and at runtime
 * `__dirname` resolves to that compiled location — not the source dir.
 * JSON read via filesystem path would look in the wrong place. A JSON
 * import is resolved by webpack at build time and inlined into the
 * bundle, sidestepping the issue.
 */

import libraryJson from "./standards_library.json";

export type Standard = {
  id: string;
  rule: string;
  correct?: string;
  incorrect?: string;
  rule_type?: "hard" | "nuanced" | string;
  checkable_from?: string;
  relevant_content_types?: string[];
  content_type_notes?: Record<string, string>;
};

export type Category = {
  id: string;
  name: string;
  standards: Standard[];
};

export type ContentType = {
  id: string;
  name: string;
  description: string;
};

export type StandardsLibrary = {
  version: string;
  total_standards: number;
  content_types: ContentType[];
  categories: Category[];
};

export function loadLibrary(): StandardsLibrary {
  return libraryJson as unknown as StandardsLibrary;
}

export function getStandard(id: string): Standard | null {
  const lib = loadLibrary();
  for (const cat of lib.categories) {
    const std = cat.standards.find((s) => s.id === id);
    if (std) return std;
  }
  return null;
}

export function categoryOfStandard(id: string): Category | null {
  const lib = loadLibrary();
  return (
    lib.categories.find((c) => c.standards.some((s) => s.id === id)) ?? null
  );
}

export function allStandardIds(): string[] {
  return loadLibrary().categories.flatMap((c) => c.standards.map((s) => s.id));
}
