/**
 * /auth/figma — dual-purpose GET handler for the Figma plugin sign-in flow.
 *
 * Two modes on the same URL, selected by query param:
 *
 *   1. Browser entry — GET /auth/figma?plugin=1&handoff=<code>
 *      Opened by the plugin via figma.openExternal(). Requires a Clerk
 *      session (redirects to /sign-in if missing). On success, forwards the
 *      browser to /auth/figma-callback?handoff=<code>, which is the
 *      component that actually writes the token into Redis.
 *
 *   2. Polling — GET /auth/figma?poll=1&handoff=<code>
 *      Called by the plugin iframe itself while the user completes sign-in
 *      in their default browser. No Clerk cookies are available on this
 *      request path (the plugin iframe is a different origin), so the
 *      handoff code is the only capability. When the callback has written
 *      the token under Redis key `figma_handoff:<code>`, we return it and
 *      DEL the key so it can't be replayed.
 *
 * Handoff codes are single-use, 5-minute TTL, and randomly generated by
 * the plugin (128 bits of entropy). They're not tied to a Clerk user until
 * the callback page runs — so leaking one before sign-in is harmless.
 */

import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { corsHeaders as baseCors, corsPreflight } from "@/lib/cors";
import {
  FIGMA_HANDOFF_REDIS_PREFIX,
  isValidHandoff,
} from "@/lib/figma-handoff";
import { getRedis } from "@/lib/redis";

// Audit S5 — same allowlist as /api/* but the cx_token transits this
// route, so we MUST forbid intermediary caching. Layer Cache-Control:
// no-store on top of the allowlist headers.
function authCorsHeaders(req: Request): Record<string, string> {
  return { ...baseCors(req), "Cache-Control": "no-store" };
}

export async function OPTIONS(req: Request) {
  return corsPreflight(req);
}

export async function GET(req: Request) {
  const url = new URL(req.url);
  const handoff = url.searchParams.get("handoff");
  const isPoll = url.searchParams.get("poll") === "1";
  const isPlugin = url.searchParams.get("plugin") === "1";

  if (!isValidHandoff(handoff)) {
    return NextResponse.json(
      { error: "Missing or invalid handoff code" },
      { status: 400, headers: authCorsHeaders(req) },
    );
  }

  // -------------------------------------------------------------------------
  // Polling path — plugin-facing JSON endpoint. Never redirects, never
  // touches Clerk. Returns {token} exactly once per handoff code.
  //
  // `GETDEL` is atomic at the Redis level: read + delete happen as a
  // single operation, so two concurrent pollers can't both walk away
  // with the same token (closes BE-M-01 from the 2026-04-22 audit).
  // -------------------------------------------------------------------------
  if (isPoll) {
    const redis = getRedis();
    const token = await redis.getdel<string>(
      FIGMA_HANDOFF_REDIS_PREFIX + handoff,
    );
    if (!token) {
      return NextResponse.json(
        { status: "pending" },
        { status: 202, headers: authCorsHeaders(req) },
      );
    }
    return NextResponse.json(
      { token },
      { status: 200, headers: authCorsHeaders(req) },
    );
  }

  // -------------------------------------------------------------------------
  // Browser entry path — needs a Clerk session. If the user isn't signed
  // in yet, hand control to Clerk's /sign-in with a redirect_url that
  // loops back through this same handler after sign-up/sign-in.
  // -------------------------------------------------------------------------
  const { userId } = await auth();
  if (!userId) {
    const returnTo = `/auth/figma?plugin=${isPlugin ? "1" : "0"}&handoff=${encodeURIComponent(
      handoff,
    )}`;
    const signIn = new URL("/sign-in", url);
    signIn.searchParams.set("redirect_url", returnTo);
    return NextResponse.redirect(signIn);
  }

  const callback = new URL("/auth/figma-callback", url);
  callback.searchParams.set("handoff", handoff);
  return NextResponse.redirect(callback);
}
