/**
 * /auth/figma — dual-purpose GET handler for the Figma plugin sign-in flow.
 *
 * Two modes on the same URL, selected by query param:
 *
 *   1. Browser entry — GET /auth/figma?plugin=1&handoff=<code>
 *      Opened by the plugin via figma.openExternal(). Requires a Clerk
 *      session (redirects to /sign-in if missing). On success, forwards the
 *      browser to /auth/figma-callback?handoff=<code>, which is the
 *      component that actually writes the token into Redis.
 *
 *   2. Polling — GET /auth/figma?poll=1&handoff=<code>
 *      Called by the plugin iframe itself while the user completes sign-in
 *      in their default browser. No Clerk cookies are available on this
 *      request path (the plugin iframe is a different origin), so the
 *      handoff code is the only capability. When the callback has written
 *      the token under Redis key `figma_handoff:<code>`, we return it and
 *      DEL the key so it can't be replayed.
 *
 * Handoff codes are single-use, 5-minute TTL, and randomly generated by
 * the plugin (128 bits of entropy). They're not tied to a Clerk user until
 * the callback page runs — so leaking one before sign-in is harmless.
 */

import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { getRedis } from "@/lib/redis";

const HANDOFF_PREFIX = "figma_handoff:";
const HANDOFF_RE = /^[A-Za-z0-9_-]{16,128}$/;

function corsHeaders(): Record<string, string> {
  // Figma plugin iframes send Origin: null. A wildcard is safe here because
  // the sensitive data (the cx_token) is gated on possession of the random
  // handoff code, not on cookie-based credentials.
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Cache-Control": "no-store",
  };
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: corsHeaders() });
}

export async function GET(req: Request) {
  const url = new URL(req.url);
  const handoff = url.searchParams.get("handoff");
  const isPoll = url.searchParams.get("poll") === "1";
  const isPlugin = url.searchParams.get("plugin") === "1";

  if (!handoff || !HANDOFF_RE.test(handoff)) {
    return NextResponse.json(
      { error: "Missing or invalid handoff code" },
      { status: 400, headers: corsHeaders() },
    );
  }

  // -------------------------------------------------------------------------
  // Polling path — plugin-facing JSON endpoint. Never redirects, never
  // touches Clerk. Returns {token} exactly once per handoff code.
  // -------------------------------------------------------------------------
  if (isPoll) {
    const redis = getRedis();
    const key = HANDOFF_PREFIX + handoff;
    const token = await redis.get<string>(key);
    if (!token) {
      return NextResponse.json(
        { status: "pending" },
        { status: 202, headers: corsHeaders() },
      );
    }
    // Consume the token — it must not be reissued to a second poller.
    await redis.del(key);
    return NextResponse.json(
      { token },
      { status: 200, headers: corsHeaders() },
    );
  }

  // -------------------------------------------------------------------------
  // Browser entry path — needs a Clerk session. If the user isn't signed
  // in yet, hand control to Clerk's /sign-in with a redirect_url that
  // loops back through this same handler after sign-up/sign-in.
  // -------------------------------------------------------------------------
  const { userId } = await auth();
  if (!userId) {
    const returnTo = `/auth/figma?plugin=${isPlugin ? "1" : "0"}&handoff=${encodeURIComponent(
      handoff,
    )}`;
    const signIn = new URL("/sign-in", url);
    signIn.searchParams.set("redirect_url", returnTo);
    return NextResponse.redirect(signIn);
  }

  const callback = new URL("/auth/figma-callback", url);
  callback.searchParams.set("handoff", handoff);
  return NextResponse.redirect(callback);
}
