/**
 * /disclaimer — public legal disclaimer page.
 *
 * Two topics covered, both auto-generated by Termageddon based on
 * the questionnaire YES answers:
 *   1. Not-legal-advice disclaimer. Defensive coverage because
 *      ContentRX reviews customer copy that touches compliance-
 *      adjacent topics (refund language, accessibility statements,
 *      privacy-policy microcopy, etc.) and a customer could plausibly
 *      read marketing copy as legal guidance. This disclaimer makes
 *      the position explicit.
 *   2. Testimonials disclaimer. Results-may-vary boilerplate. On by
 *      default for future-proofing against any customer quote, case
 *      study, or social-proof element ContentRX adds later.
 *
 * This is the one legal page where ContentRX accepts generic legal
 * voice in exchange for the auto-update value. The /privacy and
 * /terms pages are hand-crafted in voice. The disclaimer is short
 * enough and low-stakes enough that the trade-off makes sense.
 *
 * Embed mechanics: the <div id> and <Script src> values point at the
 * same Termageddon-managed policy. The script finds the div by ID
 * and replaces its inner content with the rendered policy. If the
 * script fails to load (network, JS disabled, ad-blocker), the
 * fallback link routes the visitor to the canonical Termageddon-
 * hosted version of the same content.
 *
 * Maintenance: nothing to do here. Termageddon ships updates when
 * underlying state-law disclaimer requirements change. If the embed
 * ever breaks (Termageddon-side outage, policy retracted, etc.),
 * fall back to hand-writing this in voice the same way /privacy is.
 */

import type { Metadata } from "next";
import Script from "next/script";
import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";

// Termageddon-issued policy id for the ContentRX disclaimer. The same
// id appears in the <div> attribute (target for the script) and in
// the <Script src> path (the embed script that finds and fills it).
const TERMAGEDDON_DISCLAIMER_ID = "VVhseFZHZEVla3B6VEhwMVQzYzlQUT09";

export const metadata: Metadata = {
  title: "Disclaimer. ContentRX",
  description:
    "Two short positions ContentRX takes on what this website is and isn't. Auto-updated by the policy provider when underlying legal language shifts.",
};

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-20">
      <PageHeader
        eyebrow="Disclaimer"
        title="Disclaimer"
        lede={
          <>
            Two short positions ContentRX takes on what this website
            is and isn&apos;t. The full text below is auto-updated by
            the policy provider when the underlying legal language
            shifts. The hand-written privacy and terms pages are at{" "}
            <Link
              href="/privacy"
              className="underline underline-offset-2"
            >
              /privacy
            </Link>
            {" "}and{" "}
            <Link
              href="/terms"
              className="underline underline-offset-2"
            >
              /terms
            </Link>
            .
          </>
        }
      />

      <div
        id={TERMAGEDDON_DISCLAIMER_ID}
        className="policy_embed_div mt-10 text-default"
        aria-live="polite"
        aria-busy="true"
      >
        <p className="text-quiet">
          Loading the disclaimer. If it does not load,{" "}
          <a
            rel="nofollow"
            aria-label="click here to view the disclaimer"
            href={`https://policies.termageddon.com/api/policy/${TERMAGEDDON_DISCLAIMER_ID}`}
            target="_blank"
            className="underline underline-offset-2"
          >
            click here to view it directly
          </a>
          .
        </p>
      </div>

      <Script
        src={`https://policies.termageddon.com/api/embed/${TERMAGEDDON_DISCLAIMER_ID}.js`}
        strategy="afterInteractive"
      />
    </main>
  );
}
